const express = require('express');
const router = express.Router();
const User = require('../models/User');

// All Leads
router.get('/all-leads', async (req, res) => {
    try {
        // Get page and limit from query string
        const page = parseInt(req.query.page) || 1;
        const limit = parseInt(req.query.limit) || 15;
        const skip = (page - 1) * limit;

        // Perform two operations simultaneously for speed
        const [leads, totalCount] = await Promise.all([
            User.find()
                .sort({ createdAt: -1 }) // Use the index-friendly createdAt field
                .skip(skip)
                .limit(limit)
                .lean(), // lean() makes the query much faster (returns plain JS objects)
            User.countDocuments()
        ]);

        // Send back an object, NOT just the array
        res.json({
            leads,
            totalCount
        });
    } catch (error) {
        console.error("Backend Error:", error.message);
        res.status(500).json({ error: error.message });
    }
});

// Search
router.get('/search', async (req, res) => {
    try {
        const searchTerm = req.query.query;

        // Agar search term empty hai toh empty array return karo
        if (!searchTerm || searchTerm.trim() === "") {
            return res.status(200).json([]);
        }

        const term = searchTerm.trim();

        // Regex escape: Taaki '+', '.', '(', jese characters regex ko crash na karein
        const escapedTerm = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

        // Case-insensitive regex
        const regex = new RegExp(escapedTerm, 'i');

        const results = await User.find({
            $or: [
                // 1. Client Name Search
                { client_name: { $regex: regex } },

                // 2. Email Search
                { email: { $regex: regex } },

                // 3. Website Search
                { website: { $regex: regex } },

                { company_name: { $regex: regex } },

                { "metadata.raw_format" : { $regex: regex } },

                // 4. Sent Date Search (Nested inside metadata)
                // Note: Schema mein sent_date String hai, isliye regex direct kaam karega
                { "metadata.sent_date": { $regex: regex } },

                // 5. Generated By Search (Nested inside metadata)
                { "metadata.generated_by": { $regex: regex } }
            ]
        })
            .select('-__v') // Unnecessary version key hide karne ke liye
            .limit(20)      // Performance ke liye limit lagayi hai
            .lean();        // .lean() se query faster ho jati hai (read-only mode)

        // Success response
        res.status(200).json(results);

    } catch (error) {
        console.error("Search API Error:", error);
        res.status(500).json({
            success: false,
            message: "Server error during restricted search",
            error: error.message
        });
    }
});
// Delete Multiple
router.post('/delete-multiple', async (req, res) => {
    try {
        const { ids } = req.body;
        await User.deleteMany({ _id: { $in: ids } });
        res.json({ message: "Deleted successfully" });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;