const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
  // Book1.xlsx ka 'SNo' yahan save hoga
  original_sno: {
    type: String
  },

  // Book1.xlsx ka 'Date' column
  response_date: {
    type: String
  },

  // Book1.xlsx ka 'Lead Type' (e.g., SEO)
  lead_type: {
    type: String
  },

  // 'Name' column se data aayega
  client_name: {
    type: String,
    trim: true
  },

  // Unique identification ke liye email use hoga
  email: {
    type: String,
    lowercase: true,
    trim: true,
    unique: true // Isse duplicates handle honge
  },

  phone: {
    type: String
  },

  website: {
    type: String
  },

  // 'Company' column ka data
  company_name: {
    type: String
  },

  // Book1.xlsx ka 'City' column
  location: {
    type: String
  },

  // Book1.xlsx ka 'Comments' ya custom feedback
  response_text: {
    type: String
  },

  reason_for_return: {
    type: String
  },

  agency_details: {
    type: String
  },

  lead_type: {
    type: String
  },

  industry: {
    type: String
  },
  // Nested structure for tracking
  metadata: {
    // 'Lead Generated By' column
    generated_by: { type: String },

    // 'Outreach Template' column (isme email ki body hoti hai)
    template_used: { type: String },

    // 'Date Sent' column
    sent_date: { type: String },

    // Excel file identify karne ke liye
    raw_format: { type: String, default: 'Excel_Upload' }
  },

  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Indexing for faster search on email

module.exports = mongoose.model('User', UserSchema);